=== ACNSMiddleware/grouper/signet/util/TreeXmlLoader/Tree.dtd
<!--
====================================================================
Tree.dtd
version 1.0, 01/10/2005

DTD for a Signet organizational tree

Copyright 2006 by the Board of Trustees of Stanford University
====================================================================
01/10/05 lmcrae   Created
====================================================================
-->

<!-- ++++++++++++++++++++++++++ Tree ++++++++++++++++++++++++++ -->

<!ELEMENT Tree (Id, Name, Organization*)>

<!-- +++++++++++++++++++++++ Common elements +++++++++++++++++++++++ -->

<!ELEMENT Id        (#PCDATA)>
<!ELEMENT Type      (#PCDATA)>
<!ELEMENT Name      (#PCDATA)>

<!-- ++++++++++++++++++++++++ Organization +++++++++++++++++++++++++ -->

<!ELEMENT Organization (Id, Type?, Name, Organization*)>

=== ACNSMiddleware/grouper/signet/util/TreeXmlLoader/demo_tree.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Tree SYSTEM "Tree.dtd">
<Tree> 
<Id>admin_orgs</Id>
<Name>Administrative Organizations</Name>
<Organization>
   <Id>KITN</Id>
   <Type>insitution</Type>
   <Name>Kern Institute of Technology, Northam</Name>
   <Organization>
      <Id>PRES</Id>
      <Type>vp</Type>
      <Name>Office of the President</Name>
      <Organization>
         <Id>REGISTRAR</Id>
         <Type>division</Type>
         <Name>University Registrar</Name>
         <Organization>
            <Id>ADMISSION</Id>
            <Type>office</Type>
            <Name>Admissions</Name>
         </Organization>
         <Organization>
            <Id>FINAID</Id>
            <Type>office</Type>
            <Name>Financial Aid</Name>
         </Organization>
         <Organization>
            <Id>BURSAR</Id>
            <Type>office</Type>
            <Name>Bursar</Name>
         </Organization>
         <Organization>
            <Id>STUREC</Id>
            <Type>office</Type>
            <Name>Student Records</Name>
         </Organization>
      </Organization>
      <Organization>
         <Id>HR</Id>
         <Type>division</Type>
         <Name>Human Resources</Name>
         <Organization>
            <Id>ADMIN</Id>
            <Type>office</Type>
            <Name>HR Administration</Name>
          </Organization>
         <Organization>
            <Id>BENEFITS</Id>
            <Type>office</Type>
            <Name>Benefits</Name>
         </Organization>
         <Organization>
            <Id>HRREC</Id>
            <Type>office</Type>
            <Name>HR Records</Name>
         </Organization>
         <Organization>
            <Id>SALARY</Id>
            <Type>office</Type>
            <Name>Salaries</Name>
         </Organization>
      </Organization>
      <Organization>
         <Id>CONTROLLER</Id>
         <Type>division</Type>
         <Name>Controller's Office</Name>
         <Organization>
            <Id>REQS</Id>
            <Type>office</Type>
            <Name>Requisitions</Name>
         </Organization>
      </Organization>
      <Organization>
         <Id>LIBRARY</Id>
         <Type>division</Type>
         <Name>University Library</Name>
         <Organization>
            <Id>ACQUISITIONS</Id>
            <Type>office</Type>
            <Name>Acquisitions</Name>
         </Organization>
         <Organization>
            <Id>COLLECTIONS</Id>
            <Type>office</Type>
            <Name>Collection Development</Name>
         </Organization>
         <Organization>
            <Id>RARE</Id>
            <Type>office</Type>
            <Name>Rare Books</Name>
         </Organization>
         <Organization>
            <Id>REFERENCE</Id>
            <Type>office</Type>
            <Name>Reference</Name>
         </Organization>
      </Organization>
      <Organization>
         <Id>IT</Id>
         <Type>division</Type>
         <Name>Information Technology</Name>
         <Organization>
            <Id>NETWORKING</Id>
            <Type>office</Type>
            <Name>Networking</Name>
         </Organization>
         <Organization>
            <Id>COMM</Id>
            <Type>office</Type>
            <Name>Communications</Name>
         </Organization>
         <Organization>
            <Id>ACADCOMP</Id>
            <Type>office</Type>
            <Name>Academic Computing</Name>
         </Organization>
         <Organization>
            <Id>ADMINCOMP</Id>
            <Type>office</Type>
            <Name>Administrative Computing</Name>
         </Organization>
         <Organization>
            <Id>DEVELOPMENT</Id>
            <Type>office</Type>
            <Name>Development</Name>
         </Organization>
      </Organization>
   </Organization>

   <Organization>
      <Id>PROVOST</Id>
      <Type>vp</Type>
      <Name>Office of the Provost</Name>
      <Organization>
         <Id>ARCH</Id>
         <Type>school</Type>
         <Name>School of Architecture</Name>
      </Organization>
      <Organization>
         <Id>BUSINESS</Id>
         <Type>school</Type>
         <Name>Business School</Name>
      </Organization>
      <Organization>
         <Id>ENGINEER</Id>
         <Type>school</Type>
         <Name>School of Engineering</Name>
      </Organization>
      <Organization>
         <Id>HUMSCI</Id>
         <Type>school</Type>
         <Name>Humanities &amp; Sciences</Name>
         <Organization>
            <Id>ART</Id>
            <Type>department</Type>
            <Name>Art Department</Name>
         </Organization>
         <Organization>
            <Id>ATHLETICS</Id>
            <Type>department</Type>
            <Name>Department of Athletics and Physical Education</Name>
         </Organization>
         <Organization>
            <Id>BIOLOGY</Id>
            <Type>department</Type>
            <Name>Biology</Name>
         </Organization>
         <Organization>
            <Id>CHEM</Id>
            <Type>department</Type>
            <Name>Chemistry</Name>
         </Organization>
         <Organization>
            <Id>COMPCSI</Id>
            <Type>department</Type>
            <Name>Computer Science</Name>
         </Organization>
         <Organization>
            <Id>DRAMA</Id>
            <Type>department</Type>
            <Name>Drama Department</Name>
         </Organization>
         <Organization>
            <Id>ENGLISH</Id>
            <Type>department</Type>
            <Name>English Department</Name>
         </Organization>
         <Organization>
            <Id>LIT</Id>
            <Type>department</Type>
            <Name>Literature</Name>
         </Organization>
         <Organization>
            <Id>MUSIC</Id>
            <Type>department</Type>
            <Name>Music Department</Name>
         </Organization>
         <Organization>
            <Id>PHYSICS</Id>
            <Type>department</Type>
            <Name>Physics</Name>
         </Organization>
      </Organization>
      <Organization>
         <Id>LAW</Id>
         <Type>school</Type>
         <Name>Law School</Name>
      </Organization>
      <Organization>
         <Id>MEDICINE</Id>
         <Type>school</Type>
         <Name>School of Medicine</Name>
      </Organization>
   </Organization>
</Organization>
   
</Tree>
