=== ACNSMiddleware/grouper/signet/util/SubsystemXmlLoader/Subsystem.dtd
<!--
====================================================================
edu.internet2.middleware.signet/Subsystem.dtd
version 1.0, 01/10/2005

DTD for a Signet Subsystem metadata definition

Copyright 2005 by the Board of Trustees of Stanford University
====================================================================
01/10/05 lmcrae   Created
====================================================================
-->

<!-- ++++++++++++++++++++++++++ Subsystem ++++++++++++++++++++++++++ -->

<!ELEMENT Subsystem (Id, Name, HelpText, Tree*, Scope, ChoiceSet*, Limit*, Permission*, Category*, Function*, Proxy*)>

<!-- +++++++++++++++++++++++ Common elements +++++++++++++++++++++++ -->

<!ELEMENT Id        (#PCDATA)>
<!ELEMENT Name      (#PCDATA)>
<!ELEMENT HelpText  (#PCDATA)>
<!ELEMENT Adapter   (#PCDATA)>

<!-- ++++++++++++++++++++++++++++ Scope ++++++++++++++++++++++++++++ -->

<!ELEMENT Scope        (#PCDATA)>

<!-- ++++++++++++++++++++++++++ ChoiceSet ++++++++++++++++++++++++++ -->

<!ELEMENT ChoiceSet (Id, Choice*)>

<!ELEMENT Choice    (Value, Label, Order, Rank)>
 
<!ELEMENT Value     (#PCDATA)>

<!ELEMENT Label     (#PCDATA)>

<!ELEMENT Order     (#PCDATA)>

<!ELEMENT Rank      (#PCDATA)>

<!-- ++++++++++++++++++++++++++++ Tree +++++++++++++++++++++++++++++ -->

<!ELEMENT Tree         (Id, Name, Adapter, Organization*)>

<!ELEMENT Organization (Id, Type?, Name, Organization*)>

<!ELEMENT Type         (#PCDATA)>

<!-- ++++++++++++++++++++++++++++ Limit ++++++++++++++++++++++++++++ -->

<!ELEMENT Limit            (Id, Name, HelpText, LimitChoiceSet, Renderer)>

<!ELEMENT LimitChoiceSet   (#PCDATA)>

<!ELEMENT Renderer         (#PCDATA)>

<!--  +++++++++++++++++++++++++ Permission +++++++++++++++++++++++++ -->

<!ELEMENT Permission       (Id, PermissionLimit*, PermissionPrerequisite*)>
   
<!ELEMENT PermissionLimit  (#PCDATA)>

<!ELEMENT PermissionPrerequisite  (#PCDATA)>

<!-- +++++++++++++++++++++++++++ Category +++++++++++++++++++++++++++ -->

<!ELEMENT Category (Id, Name)>

<!-- +++++++++++++++++++++++++++ Function ++++++++++++++++++++++++++ -->

<!ELEMENT Function (Id, Name, HelpText, CategoryID, FunctionPermission*)>

<!ELEMENT CategoryID   (#PCDATA)>

<!ELEMENT FunctionPermission   (#PCDATA)>

<!-- +++++++++++++++++++++++++++ Proxy ++++++++++++++++++++++++++ -->

<!ELEMENT Proxy (#PCDATA)>

=== ACNSMiddleware/grouper/signet/util/SubsystemXmlLoader/demo_library_subsystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Subsystem SYSTEM "Subsystem.dtd">
<Subsystem>
   <Id>library</Id>
   <Name>Library Management</Name>
   <HelpText>This is a sample library management subsystem for Signet.</HelpText>
   
   <!-- ++++++++++++ Declare scope ++++++++++++ -->

   <Scope>admin_orgs</Scope>

   <!-- ++++++++++++ Define ChoiceSets ++++++++++++ -->

   <ChoiceSet>
      <Id>collection</Id>
      <Choice>
         <Value>books</Value>
         <Label>Books and monographs</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>	 
      <Choice>
         <Value>electronic</Value>
         <Label>Electronic resources</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>manuscripts</Value>
         <Label>Manuscripts and rare books</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
      <Choice>
         <Value>maps</Value>
         <Label>Maps and atlases</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>
	  <Choice>
         <Value>media</Value>
         <Label>Media materials</Label>
         <Order>5</Order>
         <Rank>5</Rank>
      </Choice>
      <Choice>
         <Value>music</Value>
         <Label>Music recordings and scores</Label>
         <Order>6</Order>
         <Rank>6</Rank>
      </Choice>
      <Choice>
         <Value>serials</Value>
         <Label>Serials and periodicals</Label>
         <Order>7</Order>
         <Rank>7</Rank>
      </Choice>
      <Choice>
         <Value>slavmat</Value>
         <Label>Slavic language materials</Label>
         <Order>8</Order>
         <Rank>8</Rank>
      </Choice>
   </ChoiceSet>

   <ChoiceSet>
      <Id>metadata-action</Id>
      <Choice>
         <Value>auth</Value>
         <Label>Maintain headings and titles for authority control</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>reclass</Value>
         <Label>Reclassify materials</Label>
         <Order>2</Order>
         <Rank>2</Rank>
       </Choice>
      <Choice>
         <Value>frequency</Value>
         <Label>Change frequency or cease/resume publication</Label>
         <Order>3</Order>
         <Rank>3</Rank>
       </Choice>	   
   </ChoiceSet>
 
   <ChoiceSet>
      <Id>acquisition-action</Id>
      <Choice>
         <Value>add</Value>
         <Label>Add to catalog</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>accession</Value>
         <Label>Generate accession number</Label>
         <Order>2</Order>
         <Rank>2</Rank>
       </Choice>
   </ChoiceSet>
     
   <ChoiceSet>
      <Id>materials-action</Id>
      <Choice>
         <Value>copies</Value>
         <Label>Add copies and volumes</Label>
         <Order>1</Order>
         <Rank>1</Rank>
       </Choice>
	   <Choice>
         <Value>bind</Value>
         <Label>Bind/re-bind copies and volumes</Label>
         <Order>2</Order>
         <Rank>2</Rank>
       </Choice>		         
	   <Choice>
         <Value>deaccess</Value>
         <Label>Deaccession copies and volumes</Label>
         <Order>3</Order>
         <Rank>3</Rank>
       </Choice>  
      <Choice>
         <Value>inventory</Value>
         <Label>Inventory materials</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>
     </ChoiceSet>
   
   <ChoiceSet>
      <Id>max-dollar-amt</Id>
      <Choice>
         <Value>100</Value>
         <Label>$100</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>1000</Value>
         <Label>$1000</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>10000</Value>
         <Label>$10,000</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
      <Choice>
         <Value>0</Value>
         <Label>No limit</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>
   </ChoiceSet>
   
   <ChoiceSet>
      <Id>subject</Id>
      <Choice>
         <Value>art</Value>
         <Label>Art and architecture</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>belles-lettres</Value>
         <Label>Belles-lettres</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>history</Value>
         <Label>History</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
      <Choice>
         <Value>langlit</Value>
         <Label>Language and literature</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>
      <Choice>
         <Value>humanities</Value>
         <Label>Other humanities</Label>
         <Order>5</Order>
         <Rank>5</Rank>
      </Choice>
      <Choice>
         <Value>philosophy</Value>
         <Label>Philosophy and religion</Label>
         <Order>6</Order>
         <Rank>6</Rank>
      </Choice>
      <Choice>
         <Value>science</Value>
         <Label>Physical sciences</Label>
         <Order>7</Order>
         <Rank>7</Rank>
      </Choice>
      <Choice>
         <Value>social</Value>
         <Label>Social sciences</Label>
         <Order>8</Order>
         <Rank>8</Rank>
      </Choice>	  	  	  	  
   </ChoiceSet>
   
   <ChoiceSet>
      <Id>language</Id>
      <Choice>
         <Value>balto</Value>
         <Label>Baltic, Romanian, Hungarian</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>french</Value>
         <Label>French and Italian</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>german</Value>
         <Label>German and Dutch</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
      <Choice>
         <Value>italian</Value>
         <Label>Italian and Portuguese</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>
      <Choice>
         <Value>romanian</Value>
         <Label>Romanian and Hungarian</Label>
         <Order>5</Order>
         <Rank>5</Rank>
      </Choice>
      <Choice>
         <Value>scandinavian</Value>
         <Label>Scandinavian</Label>
         <Order>6</Order>
         <Rank>6</Rank>
      </Choice>
      <Choice>
         <Value>slavic</Value>
         <Label>Slavic</Label>
         <Order>7</Order>
         <Rank>7</Rank>
      </Choice>	  	  
   </ChoiceSet>

   <ChoiceSet>
      <Id>fines</Id>
      <Choice>
         <Value>collect</Value>
         <Label>Accept fine payment from patrons</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>override</Value>
         <Label>Accept payment, or override block</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>forgive</Value>
         <Label>Accept payment, override, or forgive fines</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
   </ChoiceSet>

   <ChoiceSet>
      <Id>access</Id>
      <Choice>
         <Value>viewmin</Value>
         <Label>View patron contact info.</Label>
         <Order>1</Order>
         <Rank>1</Rank>
      </Choice>
      <Choice>
         <Value>editmin</Value>
         <Label>Modify patron contact info.</Label>
         <Order>2</Order>
         <Rank>2</Rank>
      </Choice>
      <Choice>
         <Value>add</Value>
         <Label>Add and delete patrons; modify contact info.</Label>
         <Order>3</Order>
         <Rank>3</Rank>
      </Choice>
      <Choice>
         <Value>permissions</Value>
         <Label>Complete access, including special permissions.</Label>
         <Order>4</Order>
         <Rank>4</Rank>
      </Choice>	  
   </ChoiceSet>   

   

   <!-- ++++++++++++ Define Limits ++++++++++++ -->

   <Limit>
      <Id>collection</Id>
      <Name>Collection</Name>
      <HelpText>The collection(s) to which this privilege applies.</HelpText>
      <LimitChoiceSet>collection</LimitChoiceSet>
      <Renderer>multipleChoiceCheckboxes.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>acquisition-action</Id>
      <Name>Acquisition tasks</Name>
      <HelpText>Specific acquisition tasks this person can complete.</HelpText>
      <LimitChoiceSet>acquisition-action</LimitChoiceSet>
      <Renderer>multipleChoiceCheckboxes.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>materials-action</Id>
      <Name>Materials processing tasks</Name>
      <HelpText>Specific materials-processing tasks this person can complete.</HelpText>
      <LimitChoiceSet>materials-action</LimitChoiceSet>
      <Renderer>multipleChoiceCheckboxes.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>metadata-action</Id>
      <Name>Metadata tasks</Name>
      <HelpText>Specific metadata tasks this person can complete.</HelpText>
      <LimitChoiceSet>metadata-action</LimitChoiceSet>
      <Renderer>multipleChoiceCheckboxes.jsp</Renderer>
   </Limit>      
   
   <Limit>
      <Id>spending-limit</Id>
      <Name>Spending limit</Name>
      <HelpText>Per-item maximum cost of materials this person can purchase.</HelpText>
      <LimitChoiceSet>max-dollar-amt</LimitChoiceSet>
      <Renderer>singleChoicePullDown.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>subject</Id>
      <Name>Subject area</Name>
      <HelpText>Subject area this person is authorized to work with.</HelpText>
      <LimitChoiceSet>subject</LimitChoiceSet>
      <Renderer>singleChoicePullDown.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>language</Id>
      <Name>Language</Name>
      <HelpText>Language of materials this person is authorized to work with.</HelpText>
      <LimitChoiceSet>language</LimitChoiceSet>
      <Renderer>multipleChoiceCheckboxes.jsp</Renderer>
   </Limit>
   
   <Limit>
      <Id>fines</Id>
      <Name>Fines handling</Name>
